In [24]:
import pandas as pd

In [25]:
#Load all cleaned tables
population = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Population_cleaned.csv")
employment =  pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Employment_cleaned.csv")
income = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Income_cleaned.csv")
housing = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Housing_cleaned.csv")
education = pd.read_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\Education_cleaned.csv")

In [26]:
#Merge all tables
df = population.merge(employment, on='State', how='inner')

df = df.merge(income, on='State', how='inner')

df = df.merge(housing, on='State', how='inner')

df = df.merge(education, on='State', how='inner')

In [27]:
#View merged data
merged_df.head()

,State,Population,Armed Forces,Labor_Force,Employed,Total_Labor_Force,Not_In_Labor_Force,Unemployed,Employment_Rate,Unemployment_Rate,Median_Income,Median_Home_Value,Bachelors,Doctorate,High_School,Masters
0,Alabama,5157699,15210,2447875,2344294,2463085,1697053,103581,95.77,4.23,66659,233300,637543,51280,870724,304002
1,Alaska,740133,26882,363709,342028,390591,195492,21681,94.04,5.96,95665,376500,97736,7132,118875,44758
2,Arizona,7582384,23856,3778884,3606425,3802740,2391066,172459,95.44,4.56,81486,426000,1101882,86023,1019002,522445
3,Arkansas,3088354,6395,1454780,1399240,1461175,1016030,55540,96.18,3.82,62106,215600,359274,22866,575871,155632
4,California,39431263,148959,20454381,19240700,20603340,11486404,1213681,94.07,5.93,100149,759500,6355683,554953,4924307,2806213

In [28]:
#Affordability Score
df['Affordability_Score'] = ((
    df['Median_Income'] /
    df['Median_Home_Value']
) * 100).round(2)

In [29]:
#Bachelor Rate
df['Bachelor_Rate'] =( (
df['Bachelors'] /
df['Population']
) * 100).round(2)

In [30]:
#Opportunity Score
df['Opportunity_Score'] = ((
    df['Median_Income'] * 0.4
    +
    df['Employment_Rate'] * 1000 * 0.3
    +
    df['Bachelor_Rate'] * 1000 * 0.3
)).round(2)

In [31]:
df.head()

,State,Population,Labor_Force,Employed,Unemployed,Employment_Rate,Unemployment_Rate,Median_Income,Median_Home_Value,Bachelors,Doctorate,High_School,Masters,Affordability_Score,Bachelor_Rate,Opportunity_Score
0,Alabama,5157699,2447875,2344294,103581,95.77,4.23,66659,233300,637543,51280,870724,304002,28.57,12.36,59102.6
1,Alaska,740133,363709,342028,21681,94.04,5.96,95665,376500,97736,7132,118875,44758,25.41,13.21,70441.0
2,Arizona,7582384,3778884,3606425,172459,95.44,4.56,81486,426000,1101882,86023,1019002,522445,19.13,14.53,65585.4
3,Arkansas,3088354,1454780,1399240,55540,96.18,3.82,62106,215600,359274,22866,575871,155632,28.81,11.63,57185.4
4,California,39431263,20454381,19240700,1213681,94.07,5.93,100149,759500,6355683,554953,4924307,2806213,13.19,16.12,73116.6

In [32]:
#save the file
df.to_csv(r"C:\Users\chhay\Documents\Project\American Community Survey (ACS)\Cleaned_Data\ACS_Master_Dataset.csv", index=False
)